//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/_Scripts/Juego/Input/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Inputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Inputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""MovimientoLibre"",
            ""id"": ""e7fcdf1a-1ddc-4a51-9a66-7777e15c47af"",
            ""actions"": [
                {
                    ""name"": ""Mover"",
                    ""type"": ""Value"",
                    ""id"": ""1f0514e1-9b96-4f78-950b-c5c6bc1a6d21"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Mirar"",
                    ""type"": ""Value"",
                    ""id"": ""f20a8ec8-e08d-4d90-8d52-ac322684ad33"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interactuar"",
                    ""type"": ""Button"",
                    ""id"": ""3f1fb61f-794f-494a-9d33-4c0f050e8789"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""d9a8792c-4c28-4c53-a534-2a36c7ac1e7a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Flechas"",
                    ""id"": ""00433930-f527-46c7-ac80-a8d51acb9893"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1984a672-da69-4f52-a905-5b331443ee42"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a7909742-9e01-4aa0-aab8-08c9b46ece56"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0f227a72-5e28-485f-95cc-ffc6b1bbfbac"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0bac7864-b2d9-4934-89f0-c8b980d49e2e"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""AWSD"",
                    ""id"": ""9504009f-134f-4340-923d-9eda75d3d5d2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""12a90f8e-a722-4d9a-9a21-1814001d30a4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""90d9330e-3552-47cb-8b63-2e20fba19148"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7074404d-3557-4b80-985b-8e9af99a0132"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f1480d4c-d33f-4e09-b3f3-c961eab70174"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""50c2d45b-ffb0-43b5-8d27-f635dd405a16"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mirar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a06a9bad-af36-4e3c-9fe7-1233950cec9e"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interactuar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08bde963-3d38-4642-8fe9-fe9f777fb52c"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MovimientoInterfaz"",
            ""id"": ""1e23e07f-c40d-472d-b6bd-30d10fee6d3c"",
            ""actions"": [
                {
                    ""name"": ""Salir"",
                    ""type"": ""Button"",
                    ""id"": ""96cdb1c8-ca93-49df-9bb5-67af7117b771"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Navegar"",
                    ""type"": ""Value"",
                    ""id"": ""7bb35c0b-ac9f-472d-a93c-de53a45caea2"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0b12dbb7-327c-48a2-ac6d-a086bd92c291"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""PassThrough"",
                    ""id"": ""28a54d8b-9895-4182-a722-fefb1afdad85"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a2206b61-e1f7-41d0-8798-8cf346646515"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiddleClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ce4a7064-712b-4099-91dc-93564c146fea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f22351ad-15dc-458c-b3da-c197bd9228cb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b2e19a60-e7f5-42dd-b57d-a1677351859f"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Salir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""AD"",
                    ""id"": ""cdc44e1a-d362-4181-8ca3-6368c33ffec8"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""e36055fa-97b0-47e3-ae17-53299a447764"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""991d6101-865d-4d7e-8d2e-55259aa15e65"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6d39547e-0c39-4e2c-88fb-8646bcd9c9bd"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8807b112-5a8b-45a7-a9a7-f8e3e65f2f1d"",
                    ""path"": ""<Pen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a11bfa81-e8c0-4e6b-8f6c-1f69ae5f576b"",
                    ""path"": ""<Touchscreen>/touch*/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34938831-3a00-4527-b4c1-6ee8e812292b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e029f90f-8330-437f-b154-7880a0679f42"",
                    ""path"": ""<Pen>/tip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1c525cd-2476-4ccd-ac72-85cd1434013e"",
                    ""path"": ""<Touchscreen>/touch*/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a75bbe3-0b51-4920-837f-8ede77e961ed"",
                    ""path"": ""<XRController>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3318368-13a7-4f9a-8706-5f95e4f71a12"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8823b071-4917-4b74-ba26-61cc3ddcbebc"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""MiddleClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e07e245f-89cc-402c-87b7-3a8cc8ec4bed"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MovimientoLibre
        m_MovimientoLibre = asset.FindActionMap("MovimientoLibre", throwIfNotFound: true);
        m_MovimientoLibre_Mover = m_MovimientoLibre.FindAction("Mover", throwIfNotFound: true);
        m_MovimientoLibre_Mirar = m_MovimientoLibre.FindAction("Mirar", throwIfNotFound: true);
        m_MovimientoLibre_Interactuar = m_MovimientoLibre.FindAction("Interactuar", throwIfNotFound: true);
        m_MovimientoLibre_Menu = m_MovimientoLibre.FindAction("Menu", throwIfNotFound: true);
        // MovimientoInterfaz
        m_MovimientoInterfaz = asset.FindActionMap("MovimientoInterfaz", throwIfNotFound: true);
        m_MovimientoInterfaz_Salir = m_MovimientoInterfaz.FindAction("Salir", throwIfNotFound: true);
        m_MovimientoInterfaz_Navegar = m_MovimientoInterfaz.FindAction("Navegar", throwIfNotFound: true);
        m_MovimientoInterfaz_Point = m_MovimientoInterfaz.FindAction("Point", throwIfNotFound: true);
        m_MovimientoInterfaz_Click = m_MovimientoInterfaz.FindAction("Click", throwIfNotFound: true);
        m_MovimientoInterfaz_RightClick = m_MovimientoInterfaz.FindAction("RightClick", throwIfNotFound: true);
        m_MovimientoInterfaz_MiddleClick = m_MovimientoInterfaz.FindAction("MiddleClick", throwIfNotFound: true);
        m_MovimientoInterfaz_ScrollWheel = m_MovimientoInterfaz.FindAction("ScrollWheel", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MovimientoLibre
    private readonly InputActionMap m_MovimientoLibre;
    private IMovimientoLibreActions m_MovimientoLibreActionsCallbackInterface;
    private readonly InputAction m_MovimientoLibre_Mover;
    private readonly InputAction m_MovimientoLibre_Mirar;
    private readonly InputAction m_MovimientoLibre_Interactuar;
    private readonly InputAction m_MovimientoLibre_Menu;
    public struct MovimientoLibreActions
    {
        private @Inputs m_Wrapper;
        public MovimientoLibreActions(@Inputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Mover => m_Wrapper.m_MovimientoLibre_Mover;
        public InputAction @Mirar => m_Wrapper.m_MovimientoLibre_Mirar;
        public InputAction @Interactuar => m_Wrapper.m_MovimientoLibre_Interactuar;
        public InputAction @Menu => m_Wrapper.m_MovimientoLibre_Menu;
        public InputActionMap Get() { return m_Wrapper.m_MovimientoLibre; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MovimientoLibreActions set) { return set.Get(); }
        public void SetCallbacks(IMovimientoLibreActions instance)
        {
            if (m_Wrapper.m_MovimientoLibreActionsCallbackInterface != null)
            {
                @Mover.started -= m_Wrapper.m_MovimientoLibreActionsCallbackInterface.OnMover;
                @Mover.performed -= m_Wrapper.m_MovimientoLibreActionsCallbackInterface.OnMover;
                @Mover.canceled -= m_Wrapper.m_MovimientoLibreActionsCallbackInterface.OnMover;
                @Mirar.started -= m_Wrapper.m_MovimientoLibreActionsCallbackInterface.OnMirar;
                @Mirar.performed -= m_Wrapper.m_MovimientoLibreActionsCallbackInterface.OnMirar;
                @Mirar.canceled -= m_Wrapper.m_MovimientoLibreActionsCallbackInterface.OnMirar;
                @Interactuar.started -= m_Wrapper.m_MovimientoLibreActionsCallbackInterface.OnInteractuar;
                @Interactuar.performed -= m_Wrapper.m_MovimientoLibreActionsCallbackInterface.OnInteractuar;
                @Interactuar.canceled -= m_Wrapper.m_MovimientoLibreActionsCallbackInterface.OnInteractuar;
                @Menu.started -= m_Wrapper.m_MovimientoLibreActionsCallbackInterface.OnMenu;
                @Menu.performed -= m_Wrapper.m_MovimientoLibreActionsCallbackInterface.OnMenu;
                @Menu.canceled -= m_Wrapper.m_MovimientoLibreActionsCallbackInterface.OnMenu;
            }
            m_Wrapper.m_MovimientoLibreActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Mover.started += instance.OnMover;
                @Mover.performed += instance.OnMover;
                @Mover.canceled += instance.OnMover;
                @Mirar.started += instance.OnMirar;
                @Mirar.performed += instance.OnMirar;
                @Mirar.canceled += instance.OnMirar;
                @Interactuar.started += instance.OnInteractuar;
                @Interactuar.performed += instance.OnInteractuar;
                @Interactuar.canceled += instance.OnInteractuar;
                @Menu.started += instance.OnMenu;
                @Menu.performed += instance.OnMenu;
                @Menu.canceled += instance.OnMenu;
            }
        }
    }
    public MovimientoLibreActions @MovimientoLibre => new MovimientoLibreActions(this);

    // MovimientoInterfaz
    private readonly InputActionMap m_MovimientoInterfaz;
    private IMovimientoInterfazActions m_MovimientoInterfazActionsCallbackInterface;
    private readonly InputAction m_MovimientoInterfaz_Salir;
    private readonly InputAction m_MovimientoInterfaz_Navegar;
    private readonly InputAction m_MovimientoInterfaz_Point;
    private readonly InputAction m_MovimientoInterfaz_Click;
    private readonly InputAction m_MovimientoInterfaz_RightClick;
    private readonly InputAction m_MovimientoInterfaz_MiddleClick;
    private readonly InputAction m_MovimientoInterfaz_ScrollWheel;
    public struct MovimientoInterfazActions
    {
        private @Inputs m_Wrapper;
        public MovimientoInterfazActions(@Inputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Salir => m_Wrapper.m_MovimientoInterfaz_Salir;
        public InputAction @Navegar => m_Wrapper.m_MovimientoInterfaz_Navegar;
        public InputAction @Point => m_Wrapper.m_MovimientoInterfaz_Point;
        public InputAction @Click => m_Wrapper.m_MovimientoInterfaz_Click;
        public InputAction @RightClick => m_Wrapper.m_MovimientoInterfaz_RightClick;
        public InputAction @MiddleClick => m_Wrapper.m_MovimientoInterfaz_MiddleClick;
        public InputAction @ScrollWheel => m_Wrapper.m_MovimientoInterfaz_ScrollWheel;
        public InputActionMap Get() { return m_Wrapper.m_MovimientoInterfaz; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MovimientoInterfazActions set) { return set.Get(); }
        public void SetCallbacks(IMovimientoInterfazActions instance)
        {
            if (m_Wrapper.m_MovimientoInterfazActionsCallbackInterface != null)
            {
                @Salir.started -= m_Wrapper.m_MovimientoInterfazActionsCallbackInterface.OnSalir;
                @Salir.performed -= m_Wrapper.m_MovimientoInterfazActionsCallbackInterface.OnSalir;
                @Salir.canceled -= m_Wrapper.m_MovimientoInterfazActionsCallbackInterface.OnSalir;
                @Navegar.started -= m_Wrapper.m_MovimientoInterfazActionsCallbackInterface.OnNavegar;
                @Navegar.performed -= m_Wrapper.m_MovimientoInterfazActionsCallbackInterface.OnNavegar;
                @Navegar.canceled -= m_Wrapper.m_MovimientoInterfazActionsCallbackInterface.OnNavegar;
                @Point.started -= m_Wrapper.m_MovimientoInterfazActionsCallbackInterface.OnPoint;
                @Point.performed -= m_Wrapper.m_MovimientoInterfazActionsCallbackInterface.OnPoint;
                @Point.canceled -= m_Wrapper.m_MovimientoInterfazActionsCallbackInterface.OnPoint;
                @Click.started -= m_Wrapper.m_MovimientoInterfazActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_MovimientoInterfazActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_MovimientoInterfazActionsCallbackInterface.OnClick;
                @RightClick.started -= m_Wrapper.m_MovimientoInterfazActionsCallbackInterface.OnRightClick;
                @RightClick.performed -= m_Wrapper.m_MovimientoInterfazActionsCallbackInterface.OnRightClick;
                @RightClick.canceled -= m_Wrapper.m_MovimientoInterfazActionsCallbackInterface.OnRightClick;
                @MiddleClick.started -= m_Wrapper.m_MovimientoInterfazActionsCallbackInterface.OnMiddleClick;
                @MiddleClick.performed -= m_Wrapper.m_MovimientoInterfazActionsCallbackInterface.OnMiddleClick;
                @MiddleClick.canceled -= m_Wrapper.m_MovimientoInterfazActionsCallbackInterface.OnMiddleClick;
                @ScrollWheel.started -= m_Wrapper.m_MovimientoInterfazActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.performed -= m_Wrapper.m_MovimientoInterfazActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.canceled -= m_Wrapper.m_MovimientoInterfazActionsCallbackInterface.OnScrollWheel;
            }
            m_Wrapper.m_MovimientoInterfazActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Salir.started += instance.OnSalir;
                @Salir.performed += instance.OnSalir;
                @Salir.canceled += instance.OnSalir;
                @Navegar.started += instance.OnNavegar;
                @Navegar.performed += instance.OnNavegar;
                @Navegar.canceled += instance.OnNavegar;
                @Point.started += instance.OnPoint;
                @Point.performed += instance.OnPoint;
                @Point.canceled += instance.OnPoint;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
                @MiddleClick.started += instance.OnMiddleClick;
                @MiddleClick.performed += instance.OnMiddleClick;
                @MiddleClick.canceled += instance.OnMiddleClick;
                @ScrollWheel.started += instance.OnScrollWheel;
                @ScrollWheel.performed += instance.OnScrollWheel;
                @ScrollWheel.canceled += instance.OnScrollWheel;
            }
        }
    }
    public MovimientoInterfazActions @MovimientoInterfaz => new MovimientoInterfazActions(this);
    public interface IMovimientoLibreActions
    {
        void OnMover(InputAction.CallbackContext context);
        void OnMirar(InputAction.CallbackContext context);
        void OnInteractuar(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
    }
    public interface IMovimientoInterfazActions
    {
        void OnSalir(InputAction.CallbackContext context);
        void OnNavegar(InputAction.CallbackContext context);
        void OnPoint(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
        void OnMiddleClick(InputAction.CallbackContext context);
        void OnScrollWheel(InputAction.CallbackContext context);
    }
}
